# Generated by Django 4.2 on 2024-12-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Telegram ID'),
        ),
    ]
