# Generated by Django 4.2 on 2024-12-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.PositiveIntegerField(verbose_name='Telegram ID'),
        ),
    ]
